name: EDFLY CICD with dockerhub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/edflyweb:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/edflyweb:latest
          

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop edflyweb || true
            sudo docker rm edflyweb || true
           
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/edflyweb:latest
            
            sudo docker run -d -p 80:8080 --name edflyweb --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/edflyweb:latest
            
            sudo docker ps -a